Product:
  type: object
  properties:
    _id:
      type: string
      description: The unique identifier for the product.
    id:
      type: string
      description: The unique identified for the product, assigned by the admin.
    name:
      type: string
      description: The name of the product.
    category:
      type: string
      description: The category of the product.
    price:
      type: number
      description: The price of the product.
    salePrice:
      type: number
      description: The sale price of the product.
    cost:
      type: number
      description: The cost of the product.
    description:
      type: string
      description: The description of the product.

CreateProductInput:
  type: object
  required:
    - id
    - name
    - category
    - price
    - salePrice
    - cost
  properties:
    id:
      type: string
      description: The unique identified for the product, assigned by the admin.
    name:
      type: string
      description: The name of the product
    category:
      type: string
      description: The category of the product.
    price:
      type: number
      description: The price of the product
    salePrice:
      type: number
      description: The sale price of the product.
    cost:
      type: number
      description: The cost of the product.
    description:
      type: string
      description: The description of the product.
